name: Generate owned Tonies JSON

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: read
      pull-requests: write

    steps:
      - name: Checkout Your Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: false

      - name: Clone Origin Repository
        run: git clone --depth=1 ${{ secrets.ORIGIN_REPO_URL }} origin_repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests thefuzz

      - name: Generate New JSON with "owned" Property
        run: python generate_owned_json.py

      - name: Remove Origin Repo
        run: rm -rf origin_repo

      - name: Check for Changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes detected. Exiting."
            echo "NO_CHANGES=true" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changes
        if: env.NO_CHANGES != 'true'
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git commit -m "Updated owned Tonies JSON"
          git push